/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package martinellialessandrathreadlibro;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author martinelli.alessandr
 */
/**
 * all'inizio definisco una classe jFrmLibroGara che viene estesa a javax.swing.JFrame (creo la GUI)
 * (Pausa)Serve per mettere in pausa tutti i thread (All'inizio sono tutti attivi)
 * L'array list serve a gestire più thread insieme
 * @author martinelli.alessandr
 */
public class jFrmLibroGara extends javax.swing.JFrame  {
        private boolean Pausa = false;
    private ArrayList<ProgressBar> listaThread = new ArrayList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jFrmLibroGara.class.getName());

    /**
     * Creates new form jFrmLibroGara
     */
    public jFrmLibroGara() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblThread1 = new javax.swing.JLabel();
        lblThread2 = new javax.swing.JLabel();
        lblThread3 = new javax.swing.JLabel();
        lblicona3 = new javax.swing.JLabel();
        pgb1 = new javax.swing.JProgressBar();
        lblicona2 = new javax.swing.JLabel();
        pgb2 = new javax.swing.JProgressBar();
        lblicona1 = new javax.swing.JLabel();
        pgb3 = new javax.swing.JProgressBar();
        btnAvvia = new javax.swing.JButton();
        btnPausa = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblThread1.setText("Thread 1");
        getContentPane().add(lblThread1);
        lblThread1.setBounds(14, 22, 45, 16);

        lblThread2.setText("Thread 2");
        getContentPane().add(lblThread2);
        lblThread2.setBounds(10, 190, 45, 16);

        lblThread3.setText("Thread 3");
        getContentPane().add(lblThread3);
        lblThread3.setBounds(10, 310, 45, 16);

        lblicona3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/DarkRomance/libro21 (2).png"))); // NOI18N
        getContentPane().add(lblicona3);
        lblicona3.setBounds(150, 20, 50, 80);

        pgb1.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(pgb1);
        pgb1.setBounds(157, 31, 567, 55);

        lblicona2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/DarkRomance/libro22.png"))); // NOI18N
        getContentPane().add(lblicona2);
        lblicona2.setBounds(150, 150, 93, 80);

        pgb2.setForeground(new java.awt.Color(255, 0, 153));
        getContentPane().add(pgb2);
        pgb2.setBounds(154, 164, 570, 55);

        lblicona1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Immagini/DarkRomance/libro24.png"))); // NOI18N
        getContentPane().add(lblicona1);
        lblicona1.setBounds(150, 280, 51, 80);

        pgb3.setForeground(new java.awt.Color(0, 204, 0));
        getContentPane().add(pgb3);
        pgb3.setBounds(150, 290, 570, 55);

        btnAvvia.setText("Avvia");
        btnAvvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvviaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAvvia);
        btnAvvia.setBounds(70, 450, 72, 23);

        btnPausa.setText("Pausa");
        btnPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPausa);
        btnPausa.setBounds(310, 500, 72, 23);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset);
        btnReset.setBounds(520, 450, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Mi serve per mettere in pausa i thread se sono in esecuzione
     * Lo utilizzo per riavviare i thread se sono in pausa
     * @param evt 
     */
    private void btnPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausaActionPerformed
        // TODO add your handling code here:
             if(Pausa){
            for(int i = 0; i < 3; i++){
                listaThread.get(i).riprendi();
            }  
            Pausa = false;
            btnPausa.setText("pausa");
        }
        else{
            for(int i = 0; i < 3; i++){
                listaThread.get(i).pausa();
            }  
            Pausa = true;
            btnPausa.setText("riprendi");
        }
    }//GEN-LAST:event_btnPausaActionPerformed
    /**
     * Quando si clicca sul bottone Avvia, questo viene disabilitato
     * Mi si creano i 3 thread e ognuno ha una progress bar
     * Vengono mandati in esecuzione
     * Creo un altro thread che mi controlla che tutti i 3 thread abbiano finito
     * con .showMessageDialog mostro un messaggio finale, quando tutti i thread hanno finito l'esecuzione
     * @param evt 
     */
    private void btnAvviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvviaActionPerformed
        // TODO add your handling code here:
                 btnAvvia.setEnabled(false);
        btnPausa.setEnabled(true);
        //creazione thread
        listaThread.add(new ProgressBar(pgb1));
        listaThread.add(new ProgressBar(pgb2));
        listaThread.add(new ProgressBar(pgb3));
        for(int i = 0; i < 3; i++){
            listaThread.get(i).start();
        }
        Thread t = new Thread(() -> {
            boolean finito = false;
            while (!finito) {
            finito = true;
                for (ProgressBar thread : listaThread) {
                    if (!thread.getFinito()) {
                        finito = false;
                        break;
                    }
                }
            }
            JOptionPane.showMessageDialog(this, "Thread terminati!");
        });
        t.start();
    }//GEN-LAST:event_btnAvviaActionPerformed
    /**
     * Quando si preme Reset i pulsanti vengono riportati allo stato iniziale
     * Ferma tutti i thread
     * vengono azzerate le barre
     * permette di ricominciare da zero
     * @param evt 
     */
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
          btnAvvia.setEnabled(true);
        btnPausa.setEnabled(false);
        btnPausa.setText("pausa");
        for(int i = 0; i < 3; i++){
            listaThread.get(i).ferma();
        }
        listaThread.removeAll(listaThread);
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jFrmLibroGara().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvvia;
    private javax.swing.JButton btnPausa;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblThread1;
    private javax.swing.JLabel lblThread2;
    private javax.swing.JLabel lblThread3;
    private javax.swing.JLabel lblicona1;
    private javax.swing.JLabel lblicona2;
    private javax.swing.JLabel lblicona3;
    private javax.swing.JProgressBar pgb1;
    private javax.swing.JProgressBar pgb2;
    private javax.swing.JProgressBar pgb3;
    // End of variables declaration//GEN-END:variables
}
